apiVersion: v1
kind: Service
metadata:
  name: project-chaos-frontend-node-port
  labels: {{- include "helm.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector: {{- include "helm.selectorLabels" . | nindent 4 }}
