apiVersion: v1
kind: Service
metadata:
  name: project-chaos-load-balancer-svc
  labels: { { - include "helm.labels" . | nindent 4 } }
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector: { { - include "helm.selectorLabels" . | nindent 4 } }
