# Container image configuration
image:
  repository: europe-central2-docker.pkg.dev/project-chaos-459521/project-chaos-docker-registry/project-chaos-frontend
  pullPolicy: Always
  tag: "latest"

# Override chart name
nameOverride: ""
fullnameOverride: ""

# Pod configuration
podAnnotations: {}
podLabels: {}

# Security context
podSecurityContext: {}
securityContext: {}

# Resources limits
resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 350m
    memory: 1024Mi

# Health checks
