name: Build and Deploy on Cloud Run

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'  # np. 1.0.1

jobs:
  docker-publish:
    runs-on: ubuntu-latest

    # for Workload Identity Federation
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SA_EMAIL }}

      - name: Configure Docker to use gcloud
        run: |
          gcloud auth configure-docker ${{ vars.REGION }}-docker.pkg.dev --quiet

      - name: Build, tag and push container
        id: build-image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            ${{ vars.REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ vars.ARTIFACT_REPO }}/project-chaos-frontend:${{ github.ref_name }}
            ${{ vars.REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ vars.ARTIFACT_REPO }}/project-chaos-frontend:latest

  deploy-to-cloud-run:
    runs-on: ubuntu-latest
    needs: docker-publish

    # for Workload Identity Federation
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SA_EMAIL }}

      - name: Deploy to Cloud Run using gcloud command
        env:
          SERVICE_ACCOUNT: ${{ secrets.GCP_SA_TO_RUN_WORKLOAD }}
          REGION: ${{ vars.REGION }}
          PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          ARTIFACT_REPO: ${{ vars.ARTIFACT_REPO }}
          IMAGE_TAG: ${{ github.ref_name }}
        run: |-
          gcloud run deploy project-chaos-frontend \
            --service-account=$SERVICE_ACCOUNT \
            --image=$REGION-docker.pkg.dev/$PROJECT_ID/$ARTIFACT_REPO/project-chaos-frontend:$IMAGE_TAG \
            --region=$REGION \
            --set-env-vars="NEXT_PUBLIC_OAUTH_REDIRECT_URL=/oauth2/authorization/google" \
            --platform="managed"
