name: Build Docker image and publish to Google Artifact Registry

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+" # np. 1.0.1

jobs:
  docker-publish:
    runs-on: ubuntu-latest

    # for Workload Identity Federation
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SA_EMAIL }}

      - name: Configure Docker to use gcloud
        run: |
          gcloud auth configure-docker europe-central2-docker.pkg.dev --quiet

      - name: Build, tag and push container
        id: build-image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          build-args: |
            NEXT_PUBLIC_OAUTH_REDIRECT_URL=${{ vars.NEXT_PUBLIC_OAUTH_REDIRECT_URL }}
          tags: |
            ${{ vars.REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ vars.ARTIFACT_REPO }}/project-chaos-frontend:${{ github.ref_name }}
            ${{ vars.REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ vars.ARTIFACT_REPO }}/project-chaos-frontend:latest
